In [1]:
import numpy as np
import numpy.random as rnd

In [33]:
# 21點
"""
重點：
    1. 最多抽到5張牌
    2. 總和不能夠超過21，否則為Burst
    3. 2~10點數正常，A=1(預設為1), J/Q/K =10
"""

def Black_Jack():
    suits = ['♣', '♠', '♦', '♥']
    ranks = ['A', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K']
    deck = []
    
    n = 0
    total = 0
    # 計算抽牌次數，一種花色最多4張
    times = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
    
    while(n<5):
        n += 1
        
        s = rnd.randint(1, 4)
        r = rnd.randint(1, 13)
        
        # 如果抽到的花色出現4次以內
        if (times[r-1] < 4):
            times[r-1] += 1
            # 將牌新增到抽到的牌組中
            deck.append(suits[s-1] + ranks[r-1])
            
            # 檢查總點數是否已經超過21
            if r<=10:
                total += r
                if total>21:
                    print("您抽到的牌為：",deck)
                    print("牌的點數總合為：", total)
                    print("Burst!!!")
                    break
                    
            else:
                total += 10
                if total>21:
                    print("您抽到的牌為：",deck)
                    print("牌的點數總合為：", total)
                    print("Burst!!!")
                    break
        
        # 如果抽到的花色一經出現過4次，必須重抽
        else:
            # 排除抽過的數字進行重新抽取
            r = rnd.choice(i for i in range(1, 13) if i != r)
            times[r-1] += 1
            # 將牌新增到抽到的牌組中
            deck.append(suits[s-1] + ranks[r-1])
            
            # 檢查總點數是否已經超過21
            if r<=10:
                total += r
                if total>21:
                    print("您抽到的牌為：",deck)
                    print("牌的點數總合為：", total)
                    print("Burst!!!")
                    break
                    
            else:
                total += 10
                if total>21:
                    print("您抽到的牌為：",deck)
                    print("牌的點數總合為：", total)
                    print("Burst!!!")
                    break
   
    # 最後如果沒有超過21，進行一般結果輸出
    if total <= 21:
        print("您抽到的牌為：",deck)
        print("牌的點數總合為：", total)

    
Black_Jack()

您抽到的牌為： ['♣5', '♠2', '♣3', '♣2', '♠A']
牌的點數總合為： 13


In [35]:
array = np.arange(1, 51).reshape(1, 50)
array2 = np.ones((50, 1), dtype = np.int32)

total = np.dot(array, array2)

print("1到50的總合為：", total[0][0])

1到50的總合為： 1275


In [36]:
import numpy.random as random

rnd_data = random.randn(10)

print("生成10個亂數陣列：", rnd_data)
print("最大值：", rnd_data.max())
print("最小值：", rnd_data.min())
print("總合為：", rnd_data.sum())

生成10個亂數陣列： [-0.07212882  1.02897635 -0.83886646 -1.36654601  0.88148615  1.17931509
 -0.46829597  0.09504189 -1.318434    0.47985216]
最大值： 1.1793150891428688
最小值： -1.3665460136228476
總合為： -0.3995996177515846


In [37]:
ary = np.ones((5, 5), dtype = np.int32) + 2

final = np.dot(ary, ary)

print("元素均為3的5x5矩陣的平方為：", final, sep="\n")

元素均為3的5x5矩陣的平方為：
[[45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]
 [45 45 45 45 45]]
